// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcItP5vuNpcP2NJd6i6_Xl4V7HyX4AWJs',
    appId: '1:155478859922:web:f72db78901f285306f064b',
    messagingSenderId: '155478859922',
    projectId: 'flowwise-90f95',
    authDomain: 'flowwise-90f95.firebaseapp.com',
    databaseURL: 'https://flowwise-90f95-default-rtdb.firebaseio.com',
    storageBucket: 'flowwise-90f95.firebasestorage.app',
    measurementId: 'G-1SKF8J8N31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOxH5YTdljqoT2aWuVAGuQXhUiv9Tgp8',
    appId: '1:155478859922:android:e13c43698d407da96f064b',
    messagingSenderId: '155478859922',
    projectId: 'flowwise-90f95',
    databaseURL: 'https://flowwise-90f95-default-rtdb.firebaseio.com',
    storageBucket: 'flowwise-90f95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4BQq4_7929N6NuX4XWacinaFSl2k6cDg',
    appId: '1:155478859922:ios:b8cefbcfbb0bc8126f064b',
    messagingSenderId: '155478859922',
    projectId: 'flowwise-90f95',
    databaseURL: 'https://flowwise-90f95-default-rtdb.firebaseio.com',
    storageBucket: 'flowwise-90f95.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4BQq4_7929N6NuX4XWacinaFSl2k6cDg',
    appId: '1:155478859922:ios:b8cefbcfbb0bc8126f064b',
    messagingSenderId: '155478859922',
    projectId: 'flowwise-90f95',
    databaseURL: 'https://flowwise-90f95-default-rtdb.firebaseio.com',
    storageBucket: 'flowwise-90f95.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcItP5vuNpcP2NJd6i6_Xl4V7HyX4AWJs',
    appId: '1:155478859922:web:bb88d70b6dd0b35e6f064b',
    messagingSenderId: '155478859922',
    projectId: 'flowwise-90f95',
    authDomain: 'flowwise-90f95.firebaseapp.com',
    databaseURL: 'https://flowwise-90f95-default-rtdb.firebaseio.com',
    storageBucket: 'flowwise-90f95.firebasestorage.app',
    measurementId: 'G-GYN8KWP38M',
  );
}
